name: edvancer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - jupyter
  - jupyter_contrib_nbextensions
  - pip:
    - --index-url=https://pypi.org/simple
    - --trusted-host=[pypi.org]
    - -rrequirements-dev.in
    
  cd intro-to-ml-with-python
  conda env create -f  environment-dev.yml
